=head1 NAME

DocPerl::Config - Details on the configuration setting for the DocPerl application

=head1 VERSION

This documentation refers to DocPerl::Config version 0.5.

=head1 DESCRIPTION

DocPerl's configuration is stored in the file docperl.conf which is an ini
style file.

=head2 Sections

=head3 LocalFolders

This sets parameters of the local section

=over 4

=item Path

A colon seperated list of directories to search

=item Exclude

A colon seperated list of directories to exclude from the search path

=item Match

A regular expression to decide which files to include in the list. If not
specified it will be created from the suffixes option

=item suffixes

Specifies file suffixes that can be to search for specific files. To
specify more that one suffix repeat the suffixes option multiple tiems e.g.

 suffixes: pm
 suffixes: pod
 suffixes: pl

It should replace Match for general file searching.

=back

=head3 IncFolders

The system wide installed perl modules section. Similar to LocalFolders
execpt Path is added to the global @INC path.

=head3 Templates

Sets parameters to be sent to L<Template> Toolkit

=over 4

=item Path

Sets the search path for templates

=item history_size

See L<Template> Toolkit documentation

=back

=head3 Template

This allows you to set general parameters that are passed to all templates

=head3 General

This section sets up parameters that are used for running DocPerl

=over 4

=item Data

Specifies the location of the data directory where templates and the cache are
stored.

=item Perl

The location of ther perl executable (used when creating POD files)

=item Cache

Allows you to turn off caching, which can be usefull you do not have
permissions to write to the disk.

 'on' or not set Turns on the cache
 'off' turns off caching

=item ClearCache

Allows a user of the web interface to clear the cache (which is usefull when
new modules are installed and the list page is cached and becomes out of
date)

 'on' turns on this feature
 anything else turns this off

Note: You probably should not turn this on for publicly available sites as
this could cause a lot of extra load on your server.

=back

=head2 URL Parameters

Here is a summary of the url parameters

=over 4

=item page

This effectivly sets which template is to be used as well as what processing
needs to be done. Some more important values are:

=over 4

=item list

Shows the module list page

=item pod

Shows the Plain Old Documentation for the module

=item api

Shows the API of the module (includes sub, modules used, module hirachy etc)

=item code

Syntax highlighted version of the module

=back

=item module

Sets the perl module to be displaied. This can be represented in one of two
forms: either standard perl form (Config::Std) or as a path from the list
page (inc__c__Config__Std). In path from location does not need to be specified

=item file

The file on the file system

=item location

The section that the file is from (inc,local or perl)

=item source

The relative perl file path (relative to search paths)

=item clearcache

Instructs DocPerl to clear it's cache (if allowed)

=item sidebar

Alters the link taget on the list page so that when the list page is used for
a firefox sidebar it displays the pages in the correct place.

=item

=item

=cut
