=head1 Welcome to DocPerl

Go to L<DocPerl::Install> for details on installing DocPerl or look at L<DocPerl::Config> for details on configuring DocPerl.

=head1 Things to do?

=head2 Useful Links

=over 4

=item *

L<pod::perlfunc>: Perl function documentation

=item *

L<http://sourceforge.net/tracker/?group_id=163244&atid=826975>: Bug reporting

=item *

L<http://docperl.sourceforge.net>: DocPerl home page

=back

=cut
